# Server settings  
server:  
    port: 8080
    address: 127.0.0.1
# SPRING PROFILES  
spring:         
  # DATASOURCE  
  datasource:  
      driverClass: com.mysql.jdbc.Driver  
      url: jdbc:mysql://127.0.0.1:3306/spacej?useUnicode=true&characterEncoding=utf-8  
      username: root  
      password: 123456
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.spacej.model
  mapperLocations: classpath:mapper/*.xml
  table: 
    auto: update
  model: 
    pack: com.spacej.model
  database: 
    type: mysql
